apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: killhouse
  namespace: killhouse-system
  labels:
    app.kubernetes.io/name: killhouse-ingress
    app.kubernetes.io/part-of: killhouse
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - staging.killhouselabs.duckdns.org
      secretName: killhouse-tls
  rules:
    - host: staging.killhouselabs.duckdns.org
      http:
        paths:
          - path: /scanner
            pathType: Prefix
            backend:
              service:
                name: scanner-api
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-client
                port:
                  number: 3000
